import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { register as registerSW } from './serviceWorkerRegistration';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);

// Enable PWA offline support in production.
// The service-worker.js is generated by CRA's Workbox plugin at build time.
registerSW();
